server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Currency Service
        - id: currency-service
          uri: ${SERVICE_URL:http://localhost}:8081
          predicates:
            - Path=/api/currency/**

        # Customer Service
        - id: customer-service
          uri: ${SERVICE_URL:http://localhost}:8082
          predicates:
            - Path=/api/customer/**
